### ISSUE TITLE
Regarding assignment

### ISSUE THREAD

**Issue by nagareddy81** [LetsUpgrade/AWS-Essentials#9]
Hi Team,

How can we upload the given tasks to upload in this GitHub as assignment. Should we take a screenshot?

**Comment by parimal20** [comment]
Take Screenshot of assignment, make pdf of screenshots. Create a GitHub public repository named LetsUpgrade-AWS. Upload pdf file on this repository. Then submit this repository link to the assignment submission form.

**Comment by nagareddy81** [comment]
Thank you, Parimal.
